name: the cloner

on:
  push:
    branches: [ main ]          

jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mirror:
          - repo: "jetshandpease/jet"
            cname: "shandpease.com"
          - repo: "jetshandpease/shandpea"
            cname: "shandpea.se"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set CNAME for ${{ matrix.mirror.cname }}
        run: |
          git config user.email "actions@github.com"
          git config user.name  "GitHub Action"
          echo "${{ matrix.mirror.cname }}" > CNAME
          git add CNAME
          git commit -m "Mirror: set CNAME to ${{ matrix.mirror.cname }}" --allow-empty

      - name: Push to ${{ matrix.mirror.repo }}
        env:
          PAT: ${{ secrets.MIRROR_PAT }}
        run: |
          git remote add mirror https://x-access-token:${PAT}@github.com/${{ matrix.mirror.repo }}.git
          git push --force --follow-tags mirror HEAD:main
